In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

grades_df = pd.read_csv('Student_Grades.csv')
grades_df

    Hours  Practice  TeamWork  MidTerm  FinalExam  Scores Grade
0     2.5       0.5       0.0      2.0        2.3    21.0     C
1     5.1       1.5       0.5      4.0        4.9    47.0     B
2     3.2       1.0       0.5      3.0        2.9    27.0     C
3     8.5       3.7       1.2      7.0        7.7    75.0     A
4     3.5       1.2       0.3      3.0        3.2    30.0     C
5     1.5       0.2       0.0      2.0        2.2    20.0     C
6     9.2       4.8       3.0      8.0        9.0    88.0     A
7     5.5       3.2       2.0      6.0        6.2    60.0     B
8     8.3       5.1       3.5      8.0        8.3    81.0     A
9     2.7       1.5       0.0      3.0        2.7    25.0     C
10    7.7       4.9       4.5      8.0        8.7    85.0     A
11    5.9       3.1       2.1      6.0        6.4    62.0     A
12    4.5       2.8       1.0      4.0        4.3    41.0     B
13    3.3       2.2       1.1      4.0        4.4    42.0     B
14    1.1       1.1       0.0      2.0        1.9    17.0     C
15    8.9       6.2       6.0      9.0        9.7    95.0     A
16    2.5       1.6       1.0      3.0        3.2    30.0     C
17    1.9       0.9       0.5      2.0        2.6    24.0     C
18    6.1       2.0       3.2      6.0        6.9    67.0     A
19    7.4       2.5       3.0      7.0        7.1    69.0     A
20    2.7       3.0       1.2      3.0        3.2    30.0     C
21    4.8       2.9       2.1      5.0        5.6    54.0     B
22    3.8       2.2       0.3      3.0        3.7    35.0     B
23    6.9       5.1       3.8      7.0        7.8    76.0     A
24    7.8       5.8       4.5      8.0        8.8    86.0     A
25    NaN       NaN       NaN      NaN        NaN     NaN   NaN

In [21]:
#grades_df.replace(np.nan, 'some value', inplace=True)
#grades_df.to_csv('Student_Grades.csv', index = False)

In [22]:
#grades_df = grades_df.dropna()
#xpoints = grades_df['Hours'].to_numpy()
#ypoints = grades_df['Scores'].to_numpy()
#plt.scatter(xpoints, ypoints, s = 5)
#plt.xlabel('Hours dedicated to studying')
#plt.ylabel('Score')
#plt.xlim(0,10)
#plt.ylim(0,100)
#plt.plot(xpoints, best_fit_function(xpoints), label = 'regression fit', color = 'red')

In [26]:
min = 100
for i in grades_df['Scores']:
    if float(i) < min:
        min = float(i)
print(min)

17.0

In [24]:
grades_df[grades_df['Grade'].str.contains('A')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [ ]:
grades_df['Scores'] = grades_df['Hours'].astype(str)
new_df2 = grades_df.set_index('Hours').sort_values('Hours')
new_df2.loc[1.1:5.5]

new_df3 = grades_df.rename(columns={'Hour': 'Hours Studied'})
new_df3
new_df2 = grades_df.rename_axis('Hours Studied')
new_df2

C:\Users\mecha\AppData\Local\Temp\ipykernel_26460\2886994442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grades_df['Scores'] = grades_df['Hours'].astype(str)

               Hours  Practice  TeamWork  MidTerm  FinalExam Scores Grade
Hours Studied
0                2.5       0.5       0.0      2.0        2.3    2.5     C
1                5.1       1.5       0.5      4.0        4.9    5.1     B
2                3.2       1.0       0.5      3.0        2.9    3.2     C
3                8.5       3.7       1.2      7.0        7.7    8.5     A
4                3.5       1.2       0.3      3.0        3.2    3.5     C
5                1.5       0.2       0.0      2.0        2.2    1.5     C
6                9.2       4.8       3.0      8.0        9.0    9.2     A
7                5.5       3.2       2.0      6.0        6.2    5.5     B
8                8.3       5.1       3.5      8.0        8.3    8.3     A
9                2.7       1.5       0.0      3.0        2.7    2.7     C
10               7.7       4.9       4.5      8.0        8.7    7.7     A
11               5.9       3.1       2.1      6.0        6.4    5.9     A
12               4.5       2.8       1.0      4.0        4.3    4.5     B
13               3.3       2.2       1.1      4.0        4.4    3.3     B
14               1.1       1.1       0.0      2.0        1.9    1.1     C
15               8.9       6.2       6.0      9.0        9.7    8.9     A
16               2.5       1.6       1.0      3.0        3.2    2.5     C
17               1.9       0.9       0.5      2.0        2.6    1.9     C
18               6.1       2.0       3.2      6.0        6.9    6.1     A
19               7.4       2.5       3.0      7.0        7.1    7.4     A
20               2.7       3.0       1.2      3.0        3.2    2.7     C
21               4.8       2.9       2.1      5.0        5.6    4.8     B
22               3.8       2.2       0.3      3.0        3.7    3.8     B
23               6.9       5.1       3.8      7.0        7.8    6.9     A
24               7.8       5.8       4.5      8.0        8.8    7.8     A

In [7]:
lst = grades_df.index[grades_df['Hours'] == 2.5].tolist()
lst
index = lst[1]

grades_df.iloc()

In [8]:
new_df = grades_df.set_index('Hours').sort_values('Hours')
new_df.loc[1.1:2, ['MidTerm', 'FinalExam', 'Grade']]
grades_df.iloc[[0,5], 0:4]

new_df.at[1.1, 'FinalExam']
grades_df.iat[2, 4]

np.float64(2.9)

Write a snipped of python code that goes through the values of collumn 'Score' and dtermines thr minumum score

# Regression